version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/Rent-Auto
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./frontend/Rent-Auto:/app
      - /app/node_modules
    command: npm run dev -- --host
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rent_auto

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent_auto
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: